version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=Cassandra # Nome do cluster Cassandra
      - CASSANDRA_DC=DC1 # Datacenter do Cassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch # Estratégia de snitch para a rede
    volumes:
      - ./data:/var/lib/cassandra # Volume para persistir os dados do Cassandra

